# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
pro: true

project_name: chairlift

metadata:
  description: chairlift - modern GTK4/Libadwaita system management tool
  homepage: "https://github.com/frostyard/chairlift"
  license: MIT
  maintainers:
    - "Brian Ketelsen <bketelsen@gmail.com>"

git:
  # Allow non-semver tags for snapshot builds
  ignore_tags:
    - continuous

snapshot:
  # Use a static version template that doesn't require parsing existing tags
  version_template: "{{ .ShortCommit }}-snapshot"

gomod:
  proxy: true

before:
  hooks:
    - go mod tidy


builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
    main: ./cmd/chairlift/main.go

archives:
  - files:
      - README.md
      - LICENSE


checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    contents:
      # Wrapper script
      - src: ./data/chairlift-wrapper.sh
        dst: /usr/bin/chairlift-wrapper
        file_info:
          mode: 0755
      # Desktop file
      - src: ./data/org.frostyard.ChairLift.desktop
        dst: /usr/share/applications/org.frostyard.ChairLift.desktop
      # Icons
      - src: ./data/icons/hicolor/scalable/apps/org.frostyard.ChairLift.svg
        dst: /usr/share/icons/hicolor/scalable/apps/org.frostyard.ChairLift.svg
      - src: ./data/icons/hicolor/scalable/apps/org.frostyard.ChairLift-flower.svg
        dst: /usr/share/icons/hicolor/scalable/apps/org.frostyard.ChairLift-flower.svg
      - src: ./data/icons/hicolor/symbolic/apps/org.frostyard.ChairLift-symbolic.svg
        dst: /usr/share/icons/hicolor/symbolic/apps/org.frostyard.ChairLift-symbolic.svg
      # PolicyKit policy and rules for nbc
      - src: ./data/org.frostyard.ChairLift.nbc.policy
        dst: /usr/share/polkit-1/actions/org.frostyard.ChairLift.nbc.policy
      - src: ./data/org.frostyard.ChairLift.nbc.rules
        dst: /usr/share/polkit-1/rules.d/org.frostyard.ChairLift.nbc.rules
    formats:
      - deb
      - rpm
      - apk

release:
  footer: |
    **Full Changelog**: https://github.com/bketelsen/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---

    _Released with [GoReleaser Pro](https://goreleaser.com/pro)!_

nightly:
  # Allows you to change the version of the generated nightly release.
  #
  # Note that some pipes require this to be semantic version compliant (nfpm,
  # for example).
  #
  # Default: `{{ incpatch .Version }}-{{ .ShortCommit }}-nightly`.
  # Templates: allowed.
  version_template: "{{ incmajor .Version }}-dev"

  # Tag name to create if publish_release is enabled.
  tag_name: dev

  # Whether to publish a release or not.
  # Only works on GitHub.
  publish_release: true

  # Whether to delete previous pre-releases for the same `tag_name` when
  # releasing.
  # This allows you to keep a single pre-release.
  keep_single_release: true